### ISSUE TITLE
Create Database Model and Schema

### ISSUE THREAD

**Issue by santa-mota** [CSCI-GA-2820-FA22-001/inventory#4]
**As a** Developer  
 **I need** the database models and schema
 **So that** I can create, read, update and delete products and their quantities in the warehouse management system
   
 ### Details and Assumptions
 * We will use PostgreSQL
* Each product in the inventory will have a unique identifier 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the database schema is UP and schema is deployed
 When I connect to the database and try to CREATE a new product or UPDATE/DELETE an existing product
Then the changes should be reflected in the database accordingly
 ```

**Comment by 500swapnil** [comment]
Completed in #12 and #15 .
