### ISSUE TITLE
Add Build Stage to CD Pipeline

### ISSUE THREAD

**Issue by 500swapnil** [CSCI-GA-2820-FA22-001/inventory#77]
**As a** developer
 **I need**a Build stage
 **So that** my repo can build on IBM Cloud
   
 ### Details and Assumptions
 * Add a Build stage that has a Job to checkout your code from GitHub, a Job to run your units tests with nosetests and a Job to Build a Docker Image and push it to the IBM Cloud Container Registry

**Comment by santa-mota** [comment]
![Buuld_stage_pass](https://user-images.githubusercontent.com/19650364/206594734-859da9f1-2262-4600-9148-e1690d88f725.png)
