### ISSUE TITLE
Add Deploy Stage to CD Pipeline

### ISSUE THREAD

**Issue by 500swapnil** [CSCI-GA-2820-FA22-001/inventory#78]
**As a** developer
 **I need**a Deploy stage
 **So that** my repo can deploy on IBM Cloud
   
 ### Details and Assumptions
 * Add a Dev Deploy Stage to the pipeline to deploy your microservice to the dev namespace in your Kubernetes cluster using the Docker image from the previous stage, if the previous stage completes successfully

**Comment by santa-mota** [comment]
![deploy_stage_pass](https://user-images.githubusercontent.com/19650364/206594785-1907f8ec-cc43-4376-95b8-6815a8b2e7c6.png)
